# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-17 21:00
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_name', models.CharField(db_index=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experimentSet_type', models.CharField(db_index=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(db_index=True, default='', max_length=50)),
                ('field_set', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(db_index=True, default='', max_length=200, unique=True)),
                ('project_slug', models.SlugField(help_text='A label for URL config.', max_length=31, unique=True)),
                ('project_notes', models.TextField(null=True)),
                ('project_active', models.BooleanField(default=True)),
                ('project_contributor', models.ManyToManyField(related_name='memberProject', to=settings.AUTH_USER_MODEL)),
                ('project_owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ownerProject', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_title', models.CharField(default='', max_length=200)),
                ('publication_abstract', models.CharField(max_length=400, null=True)),
                ('publication_authors', models.CharField(max_length=200, null=True)),
                ('publication_categories', models.CharField(max_length=200, null=True)),
                ('publication_data_used', models.CharField(max_length=200, null=True)),
                ('publication_date_published', models.DateField()),
                ('publication_date_revised', models.DateField()),
                ('publication_issue', models.CharField(max_length=200, null=True)),
                ('publication_journal', models.CharField(max_length=200, null=True)),
                ('publication_published_by', models.CharField(max_length=200, null=True)),
                ('publication_supplementry', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(db_index=True, max_length=100, null=True)),
                ('tag_color', models.CharField(default='Red', max_length=50)),
            ],
        ),
    ]
