# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-17 21:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_project_project_con'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_con',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerProject', to=settings.AUTH_USER_MODEL),
        ),
    ]
