# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-18 17:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20161017_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_name', models.CharField(db_index=True, default='', max_length=50)),
                ('choice_type', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JsonkeyField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(db_index=True, default='', max_length=50)),
                ('field_type', models.CharField(max_length=50, null=True)),
                ('field_set', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='Field',
        ),
    ]
