# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-25 15:23
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0006_auto_20161018_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsonObjField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(db_index=True, default='', max_length=50)),
                ('field_type', models.CharField(max_length=50, null=True)),
                ('field_set', django.contrib.postgres.fields.jsonb.JSONField()),
                ('jsonField_description', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='publication_abstract',
            new_name='pub_abstract',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='publication_title',
            new_name='pub_authors',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='publication_authors',
            new_name='pub_categories',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='publication_categories',
            new_name='pub_dataUsed',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='publication_date_published',
            new_name='pub_datePublished',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='publication_data_used',
            new_name='pub_supplementry',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='exp_analysis',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='exp_award',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='exp_document',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='exp_publication',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='exp_run',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='exp_set',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='exp_tag',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_slug',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='publication_date_revised',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='publication_issue',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='publication_journal',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='publication_published_by',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='publication_supplementry',
        ),
        migrations.AddField(
            model_name='award',
            name='award_exp',
            field=models.ManyToManyField(related_name='awardExp', to='organization.Experiment'),
        ),
        migrations.AddField(
            model_name='award',
            name='award_project',
            field=models.ManyToManyField(related_name='awardPro', to='organization.Project'),
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='exp_description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experimentset',
            name='experimentSet_description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experimentset',
            name='experimentSet_exp',
            field=models.ManyToManyField(related_name='setExp', to='organization.Experiment'),
        ),
        migrations.AddField(
            model_name='publication',
            name='pub_dateRevised',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='pub_exp',
            field=models.ManyToManyField(related_name='pubExp', to='organization.Experiment'),
        ),
        migrations.AddField(
            model_name='publication',
            name='pub_issue',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='publication',
            name='pub_journal',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='publication',
            name='pub_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_exp',
            field=models.ManyToManyField(related_name='tagExp', to='organization.Experiment'),
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tagUser', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='exp_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expType', to='organization.JsonObjField'),
        ),
    ]
