# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-25 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dryLab', '0008_auto_20161025_1523'),
        ('wetLab', '0002_auto_20161025_1523'),
        ('organization', '0007_auto_20161025_1523'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JsonkeyField',
        ),
    ]
