# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-25 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_delete_jsonkeyfield'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiment',
            old_name='exp_biosample',
            new_name='experiment_biosample',
        ),
        migrations.RenameField(
            model_name='experiment',
            old_name='exp_description',
            new_name='experiment_description',
        ),
        migrations.RenameField(
            model_name='experiment',
            old_name='exp_fields',
            new_name='experiment_fields',
        ),
        migrations.RenameField(
            model_name='experiment',
            old_name='exp_name',
            new_name='experiment_name',
        ),
        migrations.RenameField(
            model_name='experiment',
            old_name='exp_project',
            new_name='experiment_project',
        ),
        migrations.RenameField(
            model_name='experiment',
            old_name='exp_protocol',
            new_name='experiment_protocol',
        ),
        migrations.RenameField(
            model_name='experiment',
            old_name='exp_type',
            new_name='experiment_type',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='pub_abstract',
            new_name='publication_abstract',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='pub_authors',
            new_name='publication_authors',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='pub_categories',
            new_name='publication_categories',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='pub_dataUsed',
            new_name='publication_dataUsed',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='pub_datePublished',
            new_name='publication_datePublished',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='pub_dateRevised',
            new_name='publication_dateRevised',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='pub_exp',
            new_name='publication_exp',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='pub_issue',
            new_name='publication_issue',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='pub_journal',
            new_name='publication_journal',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='pub_supplementry',
            new_name='publication_supplementry',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='pub_title',
            new_name='publication_title',
        ),
    ]
