# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-25 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_auto_20161025_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsonobjfield',
            name='field_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
