# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-03 20:54
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0014_auto_20161102_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsonobjfield',
            name='field_set',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
