# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-04 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0015_auto_20161103_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment',
            name='experiment_fields',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='experiment_type',
        ),
    ]
