# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-07 19:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0016_auto_20161104_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='publication_exp',
        ),
    ]
