# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-18 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0017_remove_publication_publication_exp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiment',
            old_name='experiment_project',
            new_name='project',
        ),
    ]
