# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-19 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0019_auto_20161119_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experimentset',
            old_name='experiment_name',
            new_name='experimentSet_name',
        ),
       
    ]
