# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-19 21:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0020_auto_20161119_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentset',
            name='experimentSet_type',
        ),
    ]
