# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-19 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0021_remove_experimentset_experimentset_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentset',
            name='experimentSet_type',
            field=models.ForeignKey(default=1, help_text='The categorization of the set of experiments.', on_delete=django.db.models.deletion.CASCADE, related_name='setChoice', to='organization.Choice'),
            preserve_default=False,
        ),
    ]
