# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-19 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0023_remove_experimentset_experimentset_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentset',
            name='experimentSet_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
