# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-20 03:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0027_auto_20161120_0312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='publication_supplementry',
            new_name='publication_supplementary',
        ),
    ]
