# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-15 21:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0031_auto_20161120_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_contributor',
            field=models.ManyToManyField(blank=True, related_name='memberProject', to=settings.AUTH_USER_MODEL),
        ),
    ]
