# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-19 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0032_auto_20161215_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiment',
            old_name='experiment_imageObjects',
            new_name='imageObjects',
        ),
        migrations.RenameField(
            model_name='experiment',
            old_name='experiment_protocol',
            new_name='protocol',
        ),
    ]
