# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-19 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0033_auto_20161219_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiment',
            old_name='documents',
            new_name='document',
        ),
    ]
