# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-07 19:57
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0034_auto_20161219_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='publication_abstract',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='publication_authors',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='publication_dataUsed',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='publication_datePublished',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='publication_dateRevised',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='publication_identifiers',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='publication_issue',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='publication_journal',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='publication_supplementary',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='publication_volume',
        ),
        migrations.AddField(
            model_name='experiment',
            name='bio_rep_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='experiment_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='tec_rep_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='type',
            field=models.ForeignKey(blank=True, help_text='JsonObjField', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expType', to='organization.JsonObjField'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='variation',
            field=models.TextField(blank=True, null=True, verbose_name='protocol_variations'),
        ),
        migrations.AddField(
            model_name='publication',
            name='exp_sets_prod_in_pub',
            field=models.ForeignKey(blank=True, help_text='List of experiment sets that are produced by this publication.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pubProdSet', to='organization.ExperimentSet'),
        ),
        migrations.AddField(
            model_name='publication',
            name='exp_sets_used_in_pub',
            field=models.ForeignKey(blank=True, help_text='List of experiment sets that are used (not produced) by this publication.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pubUsedSet', to='organization.ExperimentSet'),
        ),
        migrations.AddField(
            model_name='publication',
            name='publication_id',
            field=models.CharField(default='', help_text='PMID or doi for the publication.', max_length=200),
        ),
        migrations.AddField(
            model_name='publication',
            name='publication_published_by',
            field=models.ForeignKey(help_text='Publication publisher.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pubByChoice', to='organization.Choice'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_categories',
            field=models.ForeignKey(help_text='The categorization of publications.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pubCatChoice', to='organization.Choice'),
        ),
    ]
