# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-09 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0035_auto_20170207_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='biosample_quantity',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='biosample_quantity_units',
            field=models.CharField(choices=[('g', 'g'), ('mg', 'mg'), ('μg', 'μg'), ('ml', 'ml'), ('cells', 'cells')], default='g', max_length=5),
        ),
    ]
