# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-13 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0037_auto_20170213_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='biosample_quantity_units',
            field=models.CharField(choices=[('', ''), ('g', 'g'), ('mg', 'mg'), ('μg', 'μg'), ('ml', 'ml'), ('cells', 'cells')], default='', max_length=5),
        ),
    ]
