# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-14 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0038_auto_20170213_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment',
            name='bio_rep_no',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='tec_rep_no',
        ),
    ]
