# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-17 01:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wetLab', '0043_target_target_description'),
        ('organization', '0039_auto_20170214_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentset',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experimentset',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setDoc', to='wetLab.Document'),
        ),
        migrations.AddField(
            model_name='experimentset',
            name='nonReplicate_type',
            field=models.CharField(blank=True, help_text='For non replicate experiments, please specify the type.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='attachment',
            field=models.FileField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
