# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-21 20:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0040_auto_20170217_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentset',
            name='nonReplicate_type',
        ),
    ]
