# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-06 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0041_remove_experimentset_nonreplicate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentset',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
