# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-29 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0042_auto_20170306_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='type',
            field=models.ForeignKey(default=1, help_text='JsonObjField', on_delete=django.db.models.deletion.CASCADE, related_name='expType', to='organization.JsonObjField'),
            preserve_default=False,
        ),
    ]
