# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-29 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0043_auto_20170329_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentset',
            name='experimentSet_description',
        ),
        migrations.AddField(
            model_name='experiment',
            name='experiment_alias',
            field=models.CharField(db_index=True, default='', help_text='Provide an alias name for the object for DCIC submission.', max_length=10),
        ),
        migrations.AddField(
            model_name='experimentset',
            name='experimentSet_alias',
            field=models.CharField(db_index=True, default='', help_text='Provide an alias name for the object for DCIC submission.', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='project_alias',
            field=models.CharField(db_index=True, default='', help_text='Provide an alias name for the object for DCIC submission.', max_length=10),
        ),
        migrations.AddField(
            model_name='publication',
            name='publication_alias',
            field=models.CharField(db_index=True, default='', help_text='Provide an alias name for the object for DCIC submission.', max_length=10),
        ),
    ]
