# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-29 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0049_project_dcic_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='dcic_alias',
            field=models.CharField(db_index=True, default='', help_text='Provide an alias name for the object for DCIC submission.', max_length=20, unique=True),
        ),
    ]
