# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-03 17:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0054_auto_20170403_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='experiment_name',
            field=models.CharField(db_index=True, default='', max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z-]*$', 'Only alphanumeric characters and dashes are allowed in names.')]),
        ),
    ]
