# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-14 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0056_auto_20170414_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='document',
            field=models.ForeignKey(blank=True, help_text='Documents that provide additional information (not data file).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wetLab.Document'),
        ),
    ]
