# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-25 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0058_experiment_update_dcic'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentset',
            name='update_dcic',
            field=models.BooleanField(default=False, help_text='This object needs to be updated at DCIC.'),
        ),
        migrations.AddField(
            model_name='project',
            name='update_dcic',
            field=models.BooleanField(default=False, help_text='This object needs to be updated at DCIC.'),
        ),
        migrations.AddField(
            model_name='publication',
            name='update_dcic',
            field=models.BooleanField(default=False, help_text='This object needs to be updated at DCIC.'),
        ),
    ]
