# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-18 18:02
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0004_auto_20161018_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_fields', django.contrib.postgres.fields.jsonb.JSONField()),
                ('analysis_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proType', to='organization.JsonkeyField')),
            ],
        ),
        migrations.CreateModel(
            name='FileSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileset_type', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SeqencingFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(default='', max_length=200)),
                ('file_mainPath', models.CharField(max_length=500, null=True)),
                ('file_backupPath', models.CharField(max_length=500, null=True)),
                ('file_sha256sum', models.CharField(default='', max_length=64)),
                ('file_set', models.ManyToManyField(related_name='fileSet', to='dryLab.FileSet')),
            ],
        ),
        migrations.CreateModel(
            name='SeqencingRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_name', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
