# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-18 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dryLab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='analysis_file',
            field=models.ManyToManyField(related_name='analysisFile', to='dryLab.SeqencingFile'),
        ),
        migrations.AddField(
            model_name='seqencingfile',
            name='file_run',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fileRun', to='dryLab.SeqencingRun'),
            preserve_default=False,
        ),
    ]
