# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-18 18:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dryLab', '0004_auto_20161018_1843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysis',
            options={'verbose_name': 'pizza'},
        ),
    ]
