# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-25 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20161018_1823'),
        ('dryLab', '0006_auto_20161018_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequencingRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='seqencingfile',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='seqencingfile',
            name='file_run',
        ),
        migrations.RemoveField(
            model_name='seqencingfile',
            name='file_set',
        ),
        migrations.AddField(
            model_name='analysis',
            name='analysis_exp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='analysisExp', to='organization.Experiment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysis',
            name='analysis_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='fileset',
            name='fileSet_file',
            field=models.ManyToManyField(related_name='fileSetFile', to='dryLab.SeqencingFile'),
        ),
        migrations.AddField(
            model_name='fileset',
            name='fileSet_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='fileset',
            name='fileset_description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='seqencingfile',
            name='SequencingFile_md5sum',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='seqencingfile',
            name='SequencingFile_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='analysis_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysisType', to='organization.JsonObjField'),
        ),
        migrations.AlterField(
            model_name='seqencingfile',
            name='file_backupPath',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='seqencingfile',
            name='file_mainPath',
            field=models.CharField(default='', max_length=500),
        ),
    ]
