# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-26 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_auto_20161025_2134'),
        ('dryLab', '0009_auto_20161025_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seqencingfile',
            old_name='file_backupPath',
            new_name='sequencingFile_backupPath',
        ),
        migrations.RenameField(
            model_name='seqencingfile',
            old_name='file_mainPath',
            new_name='sequencingFile_mainPath',
        ),
        migrations.RenameField(
            model_name='seqencingfile',
            old_name='SequencingFile_md5sum',
            new_name='sequencingFile_md5sum',
        ),
        migrations.RenameField(
            model_name='seqencingfile',
            old_name='SequencingFile_name',
            new_name='sequencingFile_name',
        ),
        migrations.RenameField(
            model_name='seqencingfile',
            old_name='SequencingFile_run',
            new_name='sequencingFile_run',
        ),
        migrations.RenameField(
            model_name='seqencingfile',
            old_name='file_sha256sum',
            new_name='sequencingFile_sha256sum',
        ),
        migrations.AddField(
            model_name='seqencingfile',
            name='sequencingFile_exp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fileExp', to='organization.Experiment'),
            preserve_default=False,
        ),
    ]
