# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-04 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dryLab', '0010_auto_20161026_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='analysis_type',
            field=models.ForeignKey(help_text='JsonObjField', on_delete=django.db.models.deletion.CASCADE, related_name='analysisType', to='organization.JsonObjField'),
        ),
    ]
