# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-08 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dryLab', '0012_sequencingrun_run_experiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencingrun',
            name='run_Barcode',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
    ]
