# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-08 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dryLab', '0013_sequencingrun_run_barcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sequencingrun',
            old_name='run_Barcode',
            new_name='run_Add_Barcode',
        ),
    ]
