# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-08 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dryLab', '0014_auto_20161108_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencingrun',
            name='run_Add_Barcode',
            field=models.CharField(choices=[('addBarcode', 'Yes'), ('showProject', 'No')], default='showProject', max_length=11),
        ),
    ]
