# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-14 23:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dryLab', '0015_auto_20161108_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencingrun',
            name='run_retrieval_date',
            field=models.DateField(default=datetime.datetime(2016, 11, 14, 23, 18, 38, 1785, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sequencingrun',
            name='run_submission_date',
            field=models.DateField(default=datetime.datetime(2016, 11, 14, 23, 18, 47, 352755, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
