# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-14 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dryLab', '0017_auto_20161114_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencingrun',
            name='run_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sequencingrun',
            name='run_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
