# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-15 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0017_remove_publication_publication_exp'),
        ('dryLab', '0018_auto_20161114_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencingrun',
            name='run_sequencing_center',
            field=models.ForeignKey(default=1, help_text='Where the sequencing has been done.', on_delete=django.db.models.deletion.CASCADE, related_name='runCenterChoice', to='organization.Choice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sequencingrun',
            name='run_sequencing_platform',
            field=models.ForeignKey(default=1, help_text='Sequencing platform.', on_delete=django.db.models.deletion.CASCADE, related_name='runPlatChoice', to='organization.Choice'),
            preserve_default=False,
        ),
    ]
