# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-16 16:19
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dryLab', '0022_auto_20161116_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='analysis_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
