# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-16 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dryLab', '0024_auto_20161116_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image_path',
            field=models.FilePathField(max_length=500),
        ),
    ]
