# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-17 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dryLab', '0025_auto_20161116_2242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name_plural': 'Images'},
        ),
        migrations.AlterField(
            model_name='analysis',
            name='analysis_file',
            field=models.ManyToManyField(help_text='AnalysisField', related_name='analysisFile', to='dryLab.SeqencingFile'),
        ),
    ]
