# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-17 00:16
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dryLab', '0026_auto_20161117_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='analysis_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='AnalysisField', null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='analysis_file',
            field=models.ManyToManyField(related_name='analysisFile', to='dryLab.SeqencingFile'),
        ),
    ]
