# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-17 00:17
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dryLab', '0027_auto_20161117_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='analysis_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='analysis_type',
            field=models.ForeignKey(help_text='AnalysisField', on_delete=django.db.models.deletion.CASCADE, related_name='analysisType', to='organization.JsonObjField'),
        ),
    ]
