# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-18 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dryLab', '0029_auto_20161118_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seqencingfile',
            name='project',
        ),
    ]
