# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-19 20:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dryLab', '0033_auto_20161119_1650'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fileset',
        ),
    ]
