# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-19 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0020_auto_20161119_2113'),
        ('dryLab', '0034_remove_fileset_fileset_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileSet_name', models.CharField(default='', max_length=50)),
                ('fileset_description', models.CharField(blank=True, max_length=200, null=True)),
                ('fileSet_file', models.ManyToManyField(related_name='fileSetFile', to='dryLab.SeqencingFile')),
                ('fileset_type', models.ForeignKey(help_text='The categorization of the set of files.', on_delete=django.db.models.deletion.CASCADE, related_name='fileSetChoice', to='organization.Choice')),
            ],
        ),
    ]
