# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-19 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dryLab', '0036_remove_fileset_fileset_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileset',
            name='fileSet_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
