# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-20 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0028_auto_20161120_0333'),
        ('dryLab', '0038_fileset_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageObjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImageObjects_images', models.FileField(help_text='Import image file', upload_to='uploads/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imgProject', to='organization.Project')),
            ],
        ),
    ]
