# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-20 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dryLab', '0039_imageobjects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageobjects',
            old_name='ImageObjects_images',
            new_name='imageObjects_images',
        ),
        migrations.AddField(
            model_name='imageobjects',
            name='imageObjects_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
