# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-13 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0037_auto_20170213_1554'),
        ('wetLab', '0040_auto_20170213_1554'),
        ('dryLab', '0041_auto_20170118_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequencingrun',
            name='run_sequencing_platform',
        ),
        migrations.AddField(
            model_name='seqencingfile',
            name='dbxrefs',
            field=models.CharField(blank=True, help_text='Unique identifiers from external resources, enter as a database name:identifier eg. HGNC:PARK2', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='seqencingfile',
            name='file_classification',
            field=models.CharField(blank=True, help_text='General classification group for the File (raw, processed, ancillary (eg. index files))', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='seqencingfile',
            name='file_format',
            field=models.ForeignKey(blank=True, help_text='Type of file format.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fileChoice', to='organization.Choice'),
        ),
        migrations.AddField(
            model_name='seqencingfile',
            name='file_format_specifications',
            field=models.ForeignKey(blank=True, help_text='Text or pdf files that further explain the file format', null=True, on_delete=django.db.models.deletion.CASCADE, to='wetLab.Document'),
        ),
        migrations.AddField(
            model_name='seqencingfile',
            name='paired_end',
            field=models.CharField(choices=[('', ''), ('1', '1'), ('2', '2')], default='', help_text='Which pair the file belongs to (if paired end library)', max_length=1),
        ),
        migrations.AddField(
            model_name='seqencingfile',
            name='read_length',
            field=models.IntegerField(blank=True, help_text='The length of the enzyme recognition sequence.', null=True),
        ),
        migrations.AddField(
            model_name='sequencingrun',
            name='run_sequencing_instrument',
            field=models.ForeignKey(blank=True, help_text='Instrument used for sequencing', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runInsChoice', to='organization.Choice'),
        ),
        migrations.AddField(
            model_name='sequencingrun',
            name='run_sequencing_machine',
            field=models.ForeignKey(blank=True, help_text='The lab specific name of the machine used.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runPlatChoice', to='organization.Choice'),
        ),
        migrations.AlterField(
            model_name='sequencingrun',
            name='run_sequencing_center',
            field=models.ForeignKey(blank=True, help_text='Where the sequencing has been done.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runCenterChoice', to='organization.Choice'),
        ),
    ]
