# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-13 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wetLab', '0041_auto_20170213_2201'),
        ('dryLab', '0042_auto_20170213_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequencingrun',
            name='run_Add_Barcode',
        ),
        migrations.AddField(
            model_name='seqencingfile',
            name='barcode',
            field=models.ForeignKey(blank=True, help_text='Barcode attached to the file.', null=True, on_delete=django.db.models.deletion.CASCADE, to='wetLab.Barcode'),
        ),
        migrations.AddField(
            model_name='seqencingfile',
            name='barcode_in_read',
            field=models.CharField(choices=[('', ''), ('1', '1'), ('2', '2')], default='', help_text='The read the barcode is located on.', max_length=1),
        ),
        migrations.AddField(
            model_name='seqencingfile',
            name='flowcell_details_chunk',
            field=models.CharField(blank=True, help_text='The file chunk label as assigned by Illumina software when splitting up a                                                                         fastq into specified chunk sizes, this label is used to re-assemble the chunks into the original file in the correct order.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='seqencingfile',
            name='flowcell_details_lane',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
