# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-14 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dryLab', '0043_auto_20170213_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seqencingfile',
            name='barcode',
            field=models.ForeignKey(blank=True, help_text='Barcode attached to the file.', null=True, on_delete=django.db.models.deletion.CASCADE, to='wetLab.Barcode', verbose_name='File barcode'),
        ),
    ]
