# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-21 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dryLab', '0046_auto_20170217_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seqencingfile',
            name='barcode_in_read',
            field=models.CharField(blank=True, choices=[('', ''), ('1', '1'), ('2', '2')], default='', help_text='The read the barcode is located on.', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='seqencingfile',
            name='paired_end',
            field=models.CharField(blank=True, choices=[('', ''), ('1', '1'), ('2', '2')], default='', help_text='Which pair the file belongs to (if paired end library)', max_length=1, null=True),
        ),
    ]
