# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-29 18:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dryLab', '0051_auto_20170329_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageobjects',
            old_name='imageObjects_alias',
            new_name='dcic_alias',
        ),
    ]
