# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-30 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dryLab', '0053_auto_20170329_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seqencingfile',
            name='file_classification',
            field=models.ForeignKey(blank=True, help_text='General classification group for the File (raw, processed, ancillary (eg. index files))', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fileclassChoice', to='organization.Choice'),
        ),
    ]
