# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-03 17:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dryLab', '0055_auto_20170331_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='analysis_name',
            field=models.CharField(default='', max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z-]*$', 'Only alphanumeric characters and dashes are allowed in names.')]),
        ),
        migrations.AlterField(
            model_name='fileset',
            name='fileSet_name',
            field=models.CharField(default='', max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z-]*$', 'Only alphanumeric characters and dashes are allowed in names.')]),
        ),
        migrations.AlterField(
            model_name='imageobjects',
            name='imageObjects_name',
            field=models.CharField(default='', max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z-]*$', 'Only alphanumeric characters and dashes are allowed in names.')]),
        ),
        migrations.AlterField(
            model_name='seqencingfile',
            name='sequencingFile_name',
            field=models.CharField(default='', max_length=255, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z-]*$', 'Only alphanumeric characters and dashes are allowed in names.')]),
        ),
        migrations.AlterField(
            model_name='sequencingrun',
            name='run_name',
            field=models.CharField(default='', max_length=100, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z-]*$', 'Only alphanumeric characters and dashes are allowed in names.')]),
        ),
    ]
