# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-03 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dryLab', '0057_auto_20170403_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageobjects',
            name='imageObjects_images',
            field=models.FileField(help_text='Import image file', max_length=200, upload_to='uploads/'),
        ),
    ]
