# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-03 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0055_auto_20170403_1727'),
        ('dryLab', '0058_auto_20170403_1934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageobjects',
            options={'verbose_name_plural': 'ImageObjects'},
        ),
        migrations.AddField(
            model_name='imageobjects',
            name='imageObjects_type',
            field=models.ForeignKey(default=136, help_text='The categorization of the images.', on_delete=django.db.models.deletion.CASCADE, related_name='imgChoice', to='organization.Choice'),
            preserve_default=False,
        ),
    ]
