# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-14 21:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dryLab', '0060_imageobjects_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='analysis_name',
            field=models.CharField(db_index=True, default='', max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z-]*$', 'Only alphanumeric characters and dashes are allowed in names.')]),
        ),
        migrations.AlterField(
            model_name='fileset',
            name='fileSet_name',
            field=models.CharField(db_index=True, default='', max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z-]*$', 'Only alphanumeric characters and dashes are allowed in names.')]),
        ),
        migrations.AlterField(
            model_name='imageobjects',
            name='imageObjects_name',
            field=models.CharField(db_index=True, default='', max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z-]*$', 'Only alphanumeric characters and dashes are allowed in names.')]),
        ),
        migrations.AlterField(
            model_name='seqencingfile',
            name='sequencingFile_name',
            field=models.CharField(db_index=True, default='', max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z-]*$', 'Only alphanumeric characters and dashes are allowed in names.')]),
        ),
        migrations.AlterField(
            model_name='sequencingrun',
            name='run_name',
            field=models.CharField(db_index=True, default='', max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z-]*$', 'Only alphanumeric characters and dashes are allowed in names.')]),
        ),
    ]
