# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-26 20:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dryLab', '0063_auto_20170426_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seqencingfile',
            name='file_classification',
        ),
    ]
