# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-01 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0061_auto_20170426_1541'),
        ('dryLab', '0065_auto_20170426_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='seqencingfile',
            name='related_files',
            field=models.ForeignKey(blank=True, help_text='Related file.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dryLab.SeqencingFile'),
        ),
        migrations.AddField(
            model_name='seqencingfile',
            name='relationship_type',
            field=models.ForeignKey(blank=True, help_text='Type of relation with other files.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relChoice', to='organization.Choice'),
        ),
    ]
