# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-18 18:23
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0005_experiment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biosample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biosample_fields', django.contrib.postgres.fields.jsonb.JSONField()),
                ('biosample_references', models.CharField(max_length=200, null=True)),
                ('biosample_dbxrefs', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Biosource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biosource_tissue', models.CharField(max_length=100, null=True)),
                ('biosource_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_description', models.CharField(default='', max_length=200)),
                ('document_attachment', models.FileField(upload_to='uploads/')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docChoice', to='organization.Choice')),
            ],
        ),
        migrations.CreateModel(
            name='Enzyme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enzyme_name', models.CharField(default='', max_length=50)),
                ('enzyme_recogSeq', models.CharField(max_length=20, null=True)),
                ('enzyme_siteLeng', models.CharField(max_length=20, null=True)),
                ('enzyme_cutPos', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individual_fields', django.contrib.postgres.fields.jsonb.JSONField()),
                ('individual_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indType', to='organization.JsonkeyField')),
            ],
        ),
        migrations.CreateModel(
            name='Modification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modification_fields', django.contrib.postgres.fields.jsonb.JSONField()),
                ('modification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modType', to='organization.JsonkeyField')),
            ],
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_fields', django.contrib.postgres.fields.jsonb.JSONField()),
                ('protocol_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proDoc', to='wetLab.Document')),
                ('protocol_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proType', to='organization.JsonkeyField')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_fields', django.contrib.postgres.fields.jsonb.JSONField()),
                ('treatment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatType', to='organization.JsonkeyField')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(default='', max_length=100)),
                ('vendor_description', models.CharField(default='', max_length=100)),
                ('vendor_url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='enzyme',
            name='enzyme_vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wetLab.Vendor'),
        ),
        migrations.AddField(
            model_name='biosource',
            name='biosource_individual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docChoice', to='wetLab.Individual'),
        ),
        migrations.AddField(
            model_name='biosource',
            name='biosource_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bioChoice', to='organization.Choice'),
        ),
        migrations.AddField(
            model_name='biosource',
            name='biosource_vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wetLab.Vendor'),
        ),
        migrations.AddField(
            model_name='biosample',
            name='biosample_biosource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bioSource', to='wetLab.Biosource'),
        ),
        migrations.AddField(
            model_name='biosample',
            name='biosample_individual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bioIndi', to='wetLab.Individual'),
        ),
        migrations.AddField(
            model_name='biosample',
            name='biosample_modification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bioMod', to='wetLab.Modification'),
        ),
        migrations.AddField(
            model_name='biosample',
            name='biosample_protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bioMod', to='wetLab.Protocol'),
        ),
        migrations.AddField(
            model_name='biosample',
            name='biosample_treatment',
            field=models.ManyToManyField(related_name='biotreat', to='wetLab.Treatment'),
        ),
        migrations.AddField(
            model_name='biosample',
            name='biosample_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biotype', to='organization.JsonkeyField'),
        ),
    ]
