# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-25 15:23
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_auto_20161025_1523'),
        ('dryLab', '0007_auto_20161025_1523'),
        ('wetLab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barRun', to='organization.Experiment')),
                ('barcode_name_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barChoice1', to='organization.Choice')),
                ('barcode_name_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barChoice2', to='organization.Choice')),
                ('barcode_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barRun', to='dryLab.SequencingRun')),
            ],
        ),
        migrations.RenameField(
            model_name='enzyme',
            old_name='enzyme_siteLeng',
            new_name='enzyme_siteLen',
        ),
        migrations.RemoveField(
            model_name='biosample',
            name='biosample_treatment',
        ),
        migrations.AddField(
            model_name='biosample',
            name='biosample_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='biosource',
            name='biosource_description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='biosource',
            name='biosource_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='individual',
            name='individual_name',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='modification',
            name='modification_description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='modification',
            name='modification_name',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='protocol_description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='protocol_enzyme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='proEnzyme', to='wetLab.Enzyme'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='protocol',
            name='protocol_name',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='protocol_variation',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treatment',
            name='treatment_biosample',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='treatBio', to='wetLab.Biosample'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treatment',
            name='treatment_description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='treatment_name',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='biosample',
            name='biosample_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='biosample',
            name='biosample_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biotype', to='organization.JsonObjField'),
        ),
        migrations.AlterField(
            model_name='biosource',
            name='biosource_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='individual_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indType', to='organization.JsonObjField'),
        ),
        migrations.AlterField(
            model_name='modification',
            name='modification_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modType', to='organization.JsonObjField'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='protocol_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proType', to='organization.JsonObjField'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='treatment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatType', to='organization.JsonObjField'),
        ),
    ]
