# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-25 21:33
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wetLab', '0002_auto_20161025_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biosample',
            name='biosample_dbxrefs',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='biosample',
            name='biosample_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biosample',
            name='biosample_references',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='biosample',
            name='biosample_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biotype', to='organization.JsonObjField'),
        ),
        migrations.AlterField(
            model_name='biosource',
            name='biosource_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='biosource',
            name='biosource_tissue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='biosource',
            name='biosource_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enzyme',
            name='enzyme_cutPos',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='enzyme',
            name='enzyme_recogSeq',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='enzyme',
            name='enzyme_siteLen',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='individual_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='modification',
            name='modification_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='modification',
            name='modification_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='protocol_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='protocol_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='treatment_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='treatment_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
