# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-31 18:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wetLab', '0003_auto_20161025_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='biosample',
            name='userOwner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individual',
            name='individual_dbxrefs',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='individual_documents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indDoc', to='wetLab.Document'),
        ),
        migrations.AddField(
            model_name='individual',
            name='individual_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='individual_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indVen', to='wetLab.Vendor'),
        ),
        migrations.AddField(
            model_name='modification',
            name='userOwner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='protocol',
            name='userOwner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
