# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-31 18:28
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wetLab', '0004_auto_20161031_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='individual_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
