# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-31 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wetLab', '0005_auto_20161031_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='protocol_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proDoc', to='wetLab.Document'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='protocol_enzyme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proEnzyme', to='wetLab.Enzyme'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='protocol_variation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
