# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-02 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wetLab', '0007_auto_20161102_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enzyme',
            name='enzyme_catalog_number',
            field=models.CharField(blank=True, help_text='A plain text for catalog description.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='enzyme',
            name='enzyme_description',
            field=models.CharField(blank=True, help_text='A plain text description of the enzyme.', max_length=200, null=True),
        ),
    ]
