# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-03 20:53
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wetLab', '0008_auto_20161102_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='construct',
            name='dbxrefs',
        ),
        migrations.RemoveField(
            model_name='construct',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='construct',
            name='references',
        ),
        migrations.RemoveField(
            model_name='construct',
            name='url',
        ),
        migrations.RemoveField(
            model_name='target',
            name='dbxrefs',
        ),
        migrations.RemoveField(
            model_name='target',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='target',
            name='references',
        ),
        migrations.RemoveField(
            model_name='target',
            name='target_region',
        ),
        migrations.RemoveField(
            model_name='target',
            name='url',
        ),
        migrations.AlterField(
            model_name='modification',
            name='modification_constructs',
            field=models.ForeignKey(blank=True, help_text='Recombinant constructs used to make modification.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modConstructs', to='wetLab.Construct'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='protocol_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
