# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-03 21:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wetLab', '0009_auto_20161103_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocol',
            name='protocol_fields',
        ),
        migrations.RemoveField(
            model_name='protocol',
            name='protocol_type',
        ),
    ]
