# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-03 22:27
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0015_auto_20161103_2054'),
        ('wetLab', '0011_remove_protocol_protocol_enzyme'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='protocol_enzyme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proEnzyme', to='wetLab.Enzyme'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='protocol_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='protocol_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='proType', to='organization.JsonObjField'),
            preserve_default=False,
        ),
    ]
