# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-04 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wetLab', '0012_auto_20161103_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biosample',
            name='biosample_type',
            field=models.ForeignKey(blank=True, help_text='JsonObjField', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biotype', to='organization.JsonObjField', verbose_name='Other Details'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='individual_type',
            field=models.ForeignKey(help_text='JsonObjField', on_delete=django.db.models.deletion.CASCADE, related_name='indType', to='organization.JsonObjField'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='protocol_type',
            field=models.ForeignKey(help_text='JsonObjField', on_delete=django.db.models.deletion.CASCADE, related_name='proType', to='organization.JsonObjField'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='treatment_type',
            field=models.ForeignKey(help_text='JsonObjField', on_delete=django.db.models.deletion.CASCADE, related_name='treatType', to='organization.JsonObjField'),
        ),
    ]
