# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-07 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0016_auto_20161104_1724'),
        ('wetLab', '0013_auto_20161104_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Others',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, help_text='An external resource with additional information about the object', null=True)),
                ('dbxrefs', models.CharField(blank=True, help_text='Unique identifiers from external resources.', max_length=100, null=True)),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.TextField()),
                ('documents', models.ForeignKey(blank=True, help_text='Documents that provide additional information (not data file).', null=True, on_delete=django.db.models.deletion.CASCADE, to='wetLab.Document')),
                ('references', models.ForeignKey(blank=True, help_text='The publications that provide more information about the object.', null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Publication')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TreatmentChemical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, help_text='An external resource with additional information about the object', null=True)),
                ('dbxrefs', models.CharField(blank=True, help_text='Unique identifiers from external resources.', max_length=100, null=True)),
                ('treatmentChemical_name', models.CharField(default='', max_length=50)),
                ('treatmentChemical_chemical', models.CharField(default='', max_length=50)),
                ('treatmentChemical_concentration', models.FloatField(blank=True, max_length=10, null=True)),
                ('treatmentChemical_duration', models.FloatField(blank=True, max_length=10, null=True)),
                ('treatmentChemical_temperature', models.FloatField(blank=True, max_length=10, null=True)),
                ('treatmentChemical_description', models.CharField(blank=True, max_length=200, null=True)),
                ('documents', models.ForeignKey(blank=True, help_text='Documents that provide additional information (not data file).', null=True, on_delete=django.db.models.deletion.CASCADE, to='wetLab.Document')),
                ('references', models.ForeignKey(blank=True, help_text='The publications that provide more information about the object.', null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Publication')),
                ('treatmentChemical_concentration_units', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conUnits', to='organization.Choice')),
                ('treatmentChemical_duration_units', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeUnits', to='organization.Choice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TreatmentRnai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, help_text='An external resource with additional information about the object', null=True)),
                ('dbxrefs', models.CharField(blank=True, help_text='Unique identifiers from external resources.', max_length=100, null=True)),
                ('treatmentRnai_name', models.CharField(default='', max_length=50)),
                ('treatmentRnai_target_sequence', models.CharField(blank=True, default='', help_text='The nucleotide sequence of the target region.', max_length=50, null=True)),
                ('treatmentRnai_description', models.CharField(blank=True, max_length=200, null=True)),
                ('documents', models.ForeignKey(blank=True, help_text='Documents that provide additional information (not data file).', null=True, on_delete=django.db.models.deletion.CASCADE, to='wetLab.Document')),
                ('references', models.ForeignKey(blank=True, help_text='The publications that provide more information about the object.', null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Publication')),
                ('treatmentRnai_biosample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatBio', to='wetLab.Biosample')),
                ('treatmentRnai_rnai_constructs', models.ForeignKey(blank=True, help_text='Recombinant constructs used for RNAi', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rnaiType', to='wetLab.Construct')),
                ('treatmentRnai_rnai_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rnaiType', to='organization.Choice')),
                ('treatmentRnai_rnai_vendor', models.ForeignKey(blank=True, help_text='RNAi center that provided the RNAi.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rnaiVendor', to='wetLab.Vendor')),
                ('treatmentRnai_target', models.ForeignKey(blank=True, help_text='The targeted gene or genomic region that is targeted by the modification.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rnaiVendor', to='wetLab.Target')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='references',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='treatment_biosample',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='treatment_type',
        ),
        migrations.DeleteModel(
            name='Treatment',
        ),
    ]
