# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-07 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wetLab', '0014_auto_20161107_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='others',
            name='biosample',
            field=models.ManyToManyField(related_name='otherBio', to='wetLab.Biosample'),
        ),
        migrations.AddField(
            model_name='treatmentchemical',
            name='treatmentChemical_biosample',
            field=models.ManyToManyField(related_name='treatChemBio', to='wetLab.Biosample'),
        ),
        migrations.RemoveField(
            model_name='treatmentrnai',
            name='treatmentRnai_biosample',
        ),
        migrations.AddField(
            model_name='treatmentrnai',
            name='treatmentRnai_biosample',
            field=models.ManyToManyField(related_name='treatRnaiBio', to='wetLab.Biosample'),
        ),
    ]
