# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-07 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wetLab', '0015_auto_20161107_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentchemical',
            name='treatmentChemical_biosample',
            field=models.ManyToManyField(help_text='Associated biosample', related_name='treatChemBio', to='wetLab.Biosample'),
        ),
        migrations.AlterField(
            model_name='treatmentchemical',
            name='treatmentChemical_description',
            field=models.CharField(blank=True, help_text='A plain text for catalog description.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='treatmentrnai',
            name='treatmentRnai_biosample',
            field=models.ManyToManyField(help_text='Associated biosample', related_name='treatRnaiBio', to='wetLab.Biosample'),
        ),
        migrations.AlterField(
            model_name='treatmentrnai',
            name='treatmentRnai_description',
            field=models.CharField(blank=True, help_text='A plain text for catalog description.', max_length=200, null=True),
        ),
    ]
