# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-07 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wetLab', '0016_auto_20161107_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatmentrnai',
            old_name='treatmentRnai_target_sequence',
            new_name='treatmentRnai_targetNucleotide_seq',
        ),
    ]
