# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-07 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wetLab', '0017_auto_20161107_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatmentrnai',
            old_name='treatmentRnai_targetNucleotide_seq',
            new_name='treatmentRnai_nucleotide_seq',
        ),
    ]
