# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-07 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wetLab', '0019_biosample_biosample_treatment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Others',
            new_name='Other',
        ),
        migrations.AlterField(
            model_name='biosample',
            name='biosample_modification',
            field=models.ForeignKey(blank=True, help_text="Expression or targeting vectors stably transfected to generate Crispr'ed or other genomic modification", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bioMod', to='wetLab.Modification'),
        ),
    ]
