# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-08 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wetLab', '0020_auto_20161107_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='barcode_name_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barChoice2', to='organization.Choice'),
        ),
    ]
