# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-08 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wetLab', '0021_auto_20161108_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='barcode_exp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barExp', to='organization.Experiment'),
        ),
        migrations.AlterField(
            model_name='biosource',
            name='biosource_individual',
            field=models.ForeignKey(help_text='Information on donor or individual mouse or other organism.', on_delete=django.db.models.deletion.CASCADE, related_name='sourceInd', to='wetLab.Individual'),
        ),
        migrations.AlterField(
            model_name='biosource',
            name='biosource_type',
            field=models.ForeignKey(help_text='The categorization of the biosource.', on_delete=django.db.models.deletion.CASCADE, related_name='sourceChoice', to='organization.Choice'),
        ),
        migrations.AlterField(
            model_name='biosource',
            name='biosource_vendor',
            field=models.ForeignKey(help_text='The Lab or Vendor that provided the biosource.', on_delete=django.db.models.deletion.CASCADE, related_name='sourceVendor', to='wetLab.Vendor'),
        ),
    ]
