# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-08 20:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wetLab', '0022_auto_20161108_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='userOwner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
