# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-08 21:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wetLab', '0023_individual_userowner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatmentchemical',
            old_name='treatmentChemical_biosample',
            new_name='biosample',
        ),
        migrations.RenameField(
            model_name='treatmentrnai',
            old_name='treatmentRnai_biosample',
            new_name='biosample',
        ),
    ]
