# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-20 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dryLab', '0039_imageobjects'),
        ('wetLab', '0024_auto_20161108_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='biosample',
            name='biosample_imageObjects',
            field=models.ManyToManyField(help_text='Cell growth images', related_name='bioImg', to='dryLab.ImageObjects'),
        ),
    ]
