# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-20 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wetLab', '0025_biosample_biosample_imageobjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biosample',
            name='biosample_imageObjects',
            field=models.ManyToManyField(blank=True, help_text='Cell growth images', null=True, related_name='bioImg', to='dryLab.ImageObjects'),
        ),
    ]
