# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-21 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wetLab', '0028_auto_20161121_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biosample',
            name='biosample_protocol',
            field=models.ForeignKey(blank=True, help_text='Information about biosample preparation protocols.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bioMod', to='wetLab.Protocol'),
        ),
    ]
