# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-21 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wetLab', '0029_auto_20161121_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='biosample',
            name='biosample_description',
            field=models.CharField(blank=True, help_text='A plain text for catalog description.', max_length=200, null=True),
        ),
    ]
