# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-15 21:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0032_auto_20161215_2127'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wetLab', '0030_biosample_biosample_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherTreatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, help_text='An external resource with additional information about the object', null=True)),
                ('dbxrefs', models.CharField(blank=True, help_text='Unique identifiers from external resources.', max_length=100, null=True)),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.TextField()),
                ('documents', models.ForeignKey(blank=True, help_text='Documents that provide additional information (not data file).', null=True, on_delete=django.db.models.deletion.CASCADE, to='wetLab.Document')),
                ('references', models.ForeignKey(blank=True, help_text='The publications that provide more information about the object.', null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Publication')),
                ('userOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='other',
            name='biosample',
        ),
        migrations.RemoveField(
            model_name='other',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='other',
            name='references',
        ),
        migrations.RemoveField(
            model_name='biosample',
            name='biosample_treatment',
        ),
        migrations.RemoveField(
            model_name='treatmentchemical',
            name='biosample',
        ),
        migrations.RemoveField(
            model_name='treatmentrnai',
            name='biosample',
        ),
        migrations.AddField(
            model_name='biosample',
            name='biosample_TreatmentChemical',
            field=models.ForeignKey(blank=True, help_text='Select previously created treatment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biosamTreatmentChemical', to='wetLab.TreatmentChemical'),
        ),
        migrations.AddField(
            model_name='biosample',
            name='biosample_TreatmentRnai',
            field=models.ForeignKey(blank=True, help_text='Select previously created treatment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biosamTreatmentRnai', to='wetLab.TreatmentRnai'),
        ),
        migrations.AddField(
            model_name='treatmentchemical',
            name='userOwner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treatmentrnai',
            name='userOwner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Other',
        ),
        migrations.AddField(
            model_name='biosample',
            name='biosample_OtherTreatment',
            field=models.ForeignKey(blank=True, help_text='Select previously created treatment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biosamOtherTreatment', to='wetLab.OtherTreatment'),
        ),
    ]
