# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-19 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wetLab', '0034_auto_20161219_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biosample',
            old_name='documents',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='biosource',
            old_name='documents',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='enzyme',
            old_name='documents',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='individual',
            old_name='documents',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='modification',
            old_name='documents',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='othertreatment',
            old_name='documents',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='treatmentchemical',
            old_name='documents',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='treatmentrnai',
            old_name='documents',
            new_name='document',
        ),
    ]
