# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-18 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wetLab', '0035_auto_20161219_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='construct',
            old_name='construct_designed_to_target',
            new_name='construct_designed_to_Target',
        ),
        migrations.RenameField(
            model_name='construct',
            old_name='documents',
            new_name='document',
        ),
    ]
