# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-07 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wetLab', '0036_auto_20170118_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='vendor_name',
            new_name='vendor_title',
        ),
        migrations.RemoveField(
            model_name='protocol',
            name='protocol_fields',
        ),
        migrations.RemoveField(
            model_name='protocol',
            name='type',
        ),
        migrations.RemoveField(
            model_name='protocol',
            name='variation',
        ),
        migrations.AlterField(
            model_name='biosample',
            name='biosample_OtherTreatment',
            field=models.ForeignKey(blank=True, help_text='Select previously created treatment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biosamOtherTreatment', to='wetLab.OtherTreatment'),
        ),
        migrations.AlterField(
            model_name='biosample',
            name='biosample_TreatmentChemical',
            field=models.ForeignKey(blank=True, help_text='Select previously created treatment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biosamTreatmentChemical', to='wetLab.TreatmentChemical'),
        ),
        migrations.AlterField(
            model_name='biosample',
            name='biosample_TreatmentRnai',
            field=models.ForeignKey(blank=True, help_text='Select previously created treatment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biosamTreatmentRnai', to='wetLab.TreatmentRnai'),
        ),
    ]
