# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-07 23:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wetLab', '0037_auto_20170207_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biosample',
            name='biosample_modification',
        ),
        migrations.AddField(
            model_name='biosample',
            name='modifications',
            field=models.ManyToManyField(blank=True, help_text="Expression or targeting vectors stably transfected to generate Crispr'ed or other genomic modification", related_name='bioMod', to='wetLab.Modification'),
        ),
        migrations.AddField(
            model_name='biosource',
            name='cell_line_termid',
            field=models.CharField(blank=True, help_text='EFO term ID for cell line.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='biosource',
            name='modifications',
            field=models.ManyToManyField(blank=True, help_text="Expression or targeting vectors stably transfected to generate Crispr'ed or other genomic modification.", related_name='biosMod', to='wetLab.Modification'),
        ),
        migrations.AlterField(
            model_name='biosource',
            name='biosource_vendor',
            field=models.ForeignKey(blank=True, help_text='The Lab or Vendor that provided the biosource.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourceVendor', to='wetLab.Vendor'),
        ),
        migrations.AlterField(
            model_name='biosource',
            name='protocol',
            field=models.ForeignKey(blank=True, help_text='Standard operation protocol for the cell line as determined by 4DN Cells Working Group', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bioProtocol', to='wetLab.Protocol', verbose_name='biosource_SOP_cell_line'),
        ),
    ]
