# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-08 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wetLab', '0038_auto_20170207_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biosample',
            name='biosample_OtherTreatment',
        ),
        migrations.AddField(
            model_name='biosample',
            name='biosample_OtherTreatment',
            field=models.ManyToManyField(blank=True, help_text='Select previously created treatment', related_name='biosamOtherTreatment', to='wetLab.OtherTreatment'),
        ),
        migrations.RemoveField(
            model_name='biosample',
            name='biosample_TreatmentChemical',
        ),
        migrations.AddField(
            model_name='biosample',
            name='biosample_TreatmentChemical',
            field=models.ManyToManyField(blank=True, help_text='Select previously created treatment', related_name='biosamTreatmentChemical', to='wetLab.TreatmentChemical'),
        ),
        migrations.RemoveField(
            model_name='biosample',
            name='biosample_TreatmentRnai',
        ),
        migrations.AddField(
            model_name='biosample',
            name='biosample_TreatmentRnai',
            field=models.ManyToManyField(blank=True, help_text='Select previously created treatment', related_name='biosamTreatmentRnai', to='wetLab.TreatmentRnai'),
        ),
        migrations.AlterField(
            model_name='biosample',
            name='biosample_type',
            field=models.ForeignKey(blank=True, help_text='JsonObjField', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biotype', to='organization.JsonObjField', verbose_name='BiosampleCellCulture Details'),
        ),
    ]
