# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-13 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0037_auto_20170213_1554'),
        ('wetLab', '0039_auto_20170208_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='target',
            old_name='target_genes',
            new_name='targeted_genes',
        ),
        migrations.AddField(
            model_name='construct',
            name='references',
            field=models.ForeignKey(blank=True, help_text='The publications that provide more information about the object.', null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Publication'),
        ),
        migrations.AddField(
            model_name='construct',
            name='url',
            field=models.URLField(blank=True, help_text='An external resource with additional information about the object', null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='dbxrefs',
            field=models.CharField(blank=True, help_text='Unique identifiers from external resources, enter as a database name:identifier eg. HGNC:PARK2', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='document',
            field=models.ForeignKey(blank=True, help_text='Documents that provide additional information (not data file).', null=True, on_delete=django.db.models.deletion.CASCADE, to='wetLab.Document'),
        ),
        migrations.AddField(
            model_name='target',
            name='references',
            field=models.ForeignKey(blank=True, help_text='The publications that provide more information about the object.', null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Publication'),
        ),
        migrations.AddField(
            model_name='target',
            name='targeted_region',
            field=models.ForeignKey(blank=True, help_text='The genome assembly, chromosome and coordinates of the region that is targeted', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targetGenAsm', to='wetLab.GenomicRegions'),
        ),
        migrations.AddField(
            model_name='target',
            name='url',
            field=models.URLField(blank=True, help_text='An external resource with additional information about the object', null=True),
        ),
        migrations.AlterField(
            model_name='biosample',
            name='dbxrefs',
            field=models.CharField(blank=True, help_text='Unique identifiers from external resources, enter as a database name:identifier eg. HGNC:PARK2', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='biosource',
            name='dbxrefs',
            field=models.CharField(blank=True, help_text='Unique identifiers from external resources, enter as a database name:identifier eg. HGNC:PARK2', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enzyme',
            name='dbxrefs',
            field=models.CharField(blank=True, help_text='Unique identifiers from external resources, enter as a database name:identifier eg. HGNC:PARK2', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='genomicregions',
            name='genomicRegions_genome_assembly',
            field=models.ForeignKey(help_text='The genome assembly from which the region was derived', on_delete=django.db.models.deletion.CASCADE, related_name='genAsmChoice', to='organization.Choice'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='dbxrefs',
            field=models.CharField(blank=True, help_text='Unique identifiers from external resources, enter as a database name:identifier eg. HGNC:PARK2', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modification',
            name='dbxrefs',
            field=models.CharField(blank=True, help_text='Unique identifiers from external resources, enter as a database name:identifier eg. HGNC:PARK2', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='othertreatment',
            name='dbxrefs',
            field=models.CharField(blank=True, help_text='Unique identifiers from external resources, enter as a database name:identifier eg. HGNC:PARK2', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='treatmentchemical',
            name='dbxrefs',
            field=models.CharField(blank=True, help_text='Unique identifiers from external resources, enter as a database name:identifier eg. HGNC:PARK2', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='treatmentrnai',
            name='dbxrefs',
            field=models.CharField(blank=True, help_text='Unique identifiers from external resources, enter as a database name:identifier eg. HGNC:PARK2', max_length=100, null=True),
        ),
    ]
