# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-13 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0038_auto_20170213_2201'),
        ('wetLab', '0040_auto_20170213_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barcode',
            name='barcode_exp',
        ),
        migrations.RemoveField(
            model_name='barcode',
            name='barcode_name_1',
        ),
        migrations.RemoveField(
            model_name='barcode',
            name='barcode_name_2',
        ),
        migrations.RemoveField(
            model_name='barcode',
            name='barcode_run',
        ),
        migrations.AddField(
            model_name='barcode',
            name='barcode_name',
            field=models.ForeignKey(default=87, on_delete=django.db.models.deletion.CASCADE, related_name='barChoice', to='organization.Choice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barcode',
            name='barcode_position',
            field=models.CharField(blank=True, help_text='The 1-based start position of the barcode in 5->3 orientation.', max_length=200, null=True),
        ),
    ]
