# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-14 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0039_auto_20170214_1521'),
        ('wetLab', '0041_auto_20170213_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcode',
            name='barcode_index',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='barChoice', to='organization.Choice'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='barcode',
            name='barcode_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
