# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-17 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wetLab', '0042_auto_20170214_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='target_description',
            field=models.CharField(default='', help_text='A brief plain text description of the target.', max_length=200),
        ),
    ]
