# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-21 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wetLab', '0044_auto_20170221_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='targeted_genes',
            field=models.CharField(default='', help_text='The genes that are specifically targeted - can also be derived from genomic region info', max_length=200),
        ),
    ]
