# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-21 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wetLab', '0046_auto_20170221_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='construct',
            name='construct_name',
            field=models.CharField(blank=True, help_text='Short name for construct - letters, numbers, hyphens or underscores allowed (no spaces)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='genomicregions',
            name='genomicRegions_genome_assembly',
            field=models.ForeignKey(blank=True, help_text='The genome assembly from which the region was derived', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genAsmChoice', to='organization.Choice'),
        ),
        migrations.AlterField(
            model_name='target',
            name='targeted_genes',
            field=models.CharField(blank=True, help_text='The genes that are specifically targeted - can also be derived from genomic region info', max_length=200, null=True),
        ),
    ]
