# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-29 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wetLab', '0051_auto_20170329_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='document_alias',
            new_name='dcic_alias',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='vendor_alias',
            new_name='dcic_alias',
        ),
    ]
