# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-29 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wetLab', '0052_auto_20170329_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biosample',
            old_name='biosample_alias',
            new_name='dcic_alias',
        ),
        migrations.RenameField(
            model_name='biosource',
            old_name='biosource_alias',
            new_name='dcic_alias',
        ),
        migrations.RenameField(
            model_name='construct',
            old_name='construct_alias',
            new_name='dcic_alias',
        ),
        migrations.RenameField(
            model_name='enzyme',
            old_name='enzyme_alias',
            new_name='dcic_alias',
        ),
        migrations.RenameField(
            model_name='genomicregions',
            old_name='genomicRegions_alias',
            new_name='dcic_alias',
        ),
        migrations.RenameField(
            model_name='individual',
            old_name='individual_alias',
            new_name='dcic_alias',
        ),
        migrations.RenameField(
            model_name='modification',
            old_name='modification_alias',
            new_name='dcic_alias',
        ),
        migrations.RenameField(
            model_name='protocol',
            old_name='protocol_alias',
            new_name='dcic_alias',
        ),
        migrations.RenameField(
            model_name='target',
            old_name='target_alias',
            new_name='dcic_alias',
        ),
        migrations.RenameField(
            model_name='treatmentchemical',
            old_name='treatmentChemical_alias',
            new_name='dcic_alias',
        ),
        migrations.RenameField(
            model_name='treatmentrnai',
            old_name='treatmentRnai_alias',
            new_name='dcic_alias',
        ),
    ]
