# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-29 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wetLab', '0053_auto_20170329_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biosample',
            name='dcic_alias',
            field=models.CharField(db_index=True, default='', help_text='Provide an alias name for the object for DCIC submission.', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='biosource',
            name='dcic_alias',
            field=models.CharField(db_index=True, default='', help_text='Provide an alias name for the object for DCIC submission.', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='construct',
            name='dcic_alias',
            field=models.CharField(db_index=True, default='', help_text='Provide an alias name for the object for DCIC submission.', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='dcic_alias',
            field=models.CharField(db_index=True, default='', help_text='Provide an alias name for the object for DCIC submission.', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='enzyme',
            name='dcic_alias',
            field=models.CharField(db_index=True, default='', help_text='Provide an alias name for the object for DCIC submission.', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='genomicregions',
            name='dcic_alias',
            field=models.CharField(db_index=True, default='', help_text='Provide an alias name for the object for DCIC submission.', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='dcic_alias',
            field=models.CharField(db_index=True, default='', help_text='Provide an alias name for the object for DCIC submission.', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='modification',
            name='dcic_alias',
            field=models.CharField(db_index=True, default='', help_text='Provide an alias name for the object for DCIC submission.', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='dcic_alias',
            field=models.CharField(db_index=True, default='', help_text='Provide an alias name for the object for DCIC submission.', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='dcic_alias',
            field=models.CharField(db_index=True, default='', help_text='Provide an alias name for the object for DCIC submission.', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='treatmentchemical',
            name='dcic_alias',
            field=models.CharField(db_index=True, default='', help_text='Provide an alias name for the object for DCIC submission.', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='treatmentrnai',
            name='dcic_alias',
            field=models.CharField(db_index=True, default='', help_text='Provide an alias name for the object for DCIC submission.', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='dcic_alias',
            field=models.CharField(db_index=True, default='', help_text='Provide an alias name for the object for DCIC submission.', max_length=10, unique=True),
        ),
    ]
