# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-30 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wetLab', '0054_auto_20170329_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biosample',
            name='biosample_type',
            field=models.ForeignKey(default='', help_text='JsonObjField', on_delete=django.db.models.deletion.CASCADE, related_name='biotype', to='organization.JsonObjField', verbose_name='BiosampleCellCulture Details'),
        ),
    ]
