# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-03 17:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wetLab', '0058_auto_20170403_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genomicregions',
            name='name',
            field=models.CharField(default='', help_text='Please give a name.', max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z-]*$', 'Only alphanumeric characters and dashes are allowed in names.')]),
        ),
        migrations.AlterField(
            model_name='target',
            name='name',
            field=models.CharField(default='', help_text='Please give a name.', max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z-]*$', 'Only alphanumeric characters and dashes are allowed in names.')]),
        ),
    ]
