# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-03 18:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wetLab', '0060_auto_20170403_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='construct',
            name='construct_name',
            field=models.CharField(default='', help_text='Short name for construct - letters, numbers, hyphens or underscores allowed (no spaces)', max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z-]*$', 'Only alphanumeric characters and dashes are allowed in names.')]),
        ),
    ]
