# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-03 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wetLab', '0061_auto_20170403_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatmentrnai',
            old_name='treatmentRnai_rnai_type',
            new_name='treatmentRnai_type',
        ),
        migrations.RenameField(
            model_name='treatmentrnai',
            old_name='treatmentRnai_rnai_vendor',
            new_name='treatmentRnai_vendor',
        ),
        migrations.RemoveField(
            model_name='treatmentrnai',
            name='target',
        ),
        migrations.AddField(
            model_name='treatmentrnai',
            name='treatmentRnai_target',
            field=models.ForeignKey(blank=True, help_text='The targeted gene or genomic region that is targeted by the modification.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rnaiTarget', to='wetLab.Target', verbose_name='treatmentRnai_target'),
        ),
        migrations.AlterField(
            model_name='treatmentrnai',
            name='constructs',
            field=models.ForeignKey(blank=True, help_text='Recombinant constructs used for RNAi', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rnaiType', to='wetLab.Construct', verbose_name='treatmentRnai_constructs'),
        ),
    ]
