# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-03 21:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wetLab', '0062_auto_20170403_1910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genomicregions',
            options={'verbose_name_plural': 'GenomicRegions'},
        ),
    ]
