# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-12 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wetLab', '0063_auto_20170403_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocol',
            name='document',
        ),
        migrations.AddField(
            model_name='protocol',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
