# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-18 15:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wetLab', '0066_auto_20170414_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(db_index=True, default='', help_text='Name of the document', max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z-]*$', 'Only alphanumeric characters and dashes are allowed in names.')]),
        ),
    ]
