# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-25 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wetLab', '0067_auto_20170418_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biosource',
            name='biosource_cell_line_tier',
            field=models.ForeignKey(blank=True, help_text='Tier into which the cell line has been classified', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bioCellChoice', to='organization.Choice', verbose_name='4DN cell line tier'),
        ),
        migrations.AlterField(
            model_name='biosource',
            name='protocol',
            field=models.ForeignKey(blank=True, help_text='Standard operation protocol for the cell line as determined by 4DN Cells Working Group', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bioProtocol', to='wetLab.Protocol', verbose_name='4DN SOP protocol'),
        ),
    ]
