# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-25 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wetLab', '0068_auto_20170425_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='biosample',
            name='update_dcic',
            field=models.BooleanField(default=False, help_text='This object needs to be updated at DCIC.'),
        ),
        migrations.AddField(
            model_name='biosource',
            name='update_dcic',
            field=models.BooleanField(default=False, help_text='This object needs to be updated at DCIC.'),
        ),
        migrations.AddField(
            model_name='construct',
            name='update_dcic',
            field=models.BooleanField(default=False, help_text='This object needs to be updated at DCIC.'),
        ),
        migrations.AddField(
            model_name='document',
            name='update_dcic',
            field=models.BooleanField(default=False, help_text='This object needs to be updated at DCIC.'),
        ),
        migrations.AddField(
            model_name='enzyme',
            name='update_dcic',
            field=models.BooleanField(default=False, help_text='This object needs to be updated at DCIC.'),
        ),
        migrations.AddField(
            model_name='genomicregions',
            name='update_dcic',
            field=models.BooleanField(default=False, help_text='This object needs to be updated at DCIC.'),
        ),
        migrations.AddField(
            model_name='individual',
            name='update_dcic',
            field=models.BooleanField(default=False, help_text='This object needs to be updated at DCIC.'),
        ),
        migrations.AddField(
            model_name='modification',
            name='update_dcic',
            field=models.BooleanField(default=False, help_text='This object needs to be updated at DCIC.'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='update_dcic',
            field=models.BooleanField(default=False, help_text='This object needs to be updated at DCIC.'),
        ),
        migrations.AddField(
            model_name='target',
            name='update_dcic',
            field=models.BooleanField(default=False, help_text='This object needs to be updated at DCIC.'),
        ),
        migrations.AddField(
            model_name='treatmentchemical',
            name='update_dcic',
            field=models.BooleanField(default=False, help_text='This object needs to be updated at DCIC.'),
        ),
        migrations.AddField(
            model_name='treatmentrnai',
            name='update_dcic',
            field=models.BooleanField(default=False, help_text='This object needs to be updated at DCIC.'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='update_dcic',
            field=models.BooleanField(default=False, help_text='This object needs to be updated at DCIC.'),
        ),
    ]
