# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-26 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0061_auto_20170426_1541'),
        ('wetLab', '0070_auto_20170426_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='targeted_proteins',
            field=models.CharField(blank=True, help_text='Use UniProt Protein IDs or accession (e.g. H31_HUMAN)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='targeted_rnas',
            field=models.CharField(blank=True, help_text='Use RefSeq identifiers (e.g. NM_003529.2)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='targeted_structure',
            field=models.ForeignKey(blank=True, help_text='Choose from the list.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targetChoice', to='organization.Choice'),
        ),
        migrations.AlterField(
            model_name='biosample',
            name='protocol',
            field=models.ForeignKey(blank=True, help_text='Information about biosample preparation protocols.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bioMod', to='wetLab.Protocol', verbose_name='Growth protocol'),
        ),
    ]
