# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-01 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wetLab', '0071_auto_20170426_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentchemical',
            name='treatmentChemical_concentration',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='treatmentchemical',
            name='treatmentChemical_duration',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='treatmentchemical',
            name='treatmentChemical_temperature',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
    ]
