# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-25 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wetLab', '0072_auto_20170501_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='biosample',
            name='protocols_additional',
            field=models.ManyToManyField(blank=True, help_text='Attach any authentication document for your biosample here. e.g. Fragment Analyzer document, Gel images.', related_name='bioAddProto', to='wetLab.Protocol'),
        ),
        migrations.AlterField(
            model_name='biosample',
            name='imageObjects',
            field=models.ManyToManyField(blank=True, help_text='Cell growth images, karyotype_image, morphology_image.', related_name='bioImg', to='dryLab.ImageObjects'),
        ),
        migrations.AlterField(
            model_name='biosample',
            name='protocol',
            field=models.ForeignKey(blank=True, help_text='Information about biosample preparation protocols.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bioProto', to='wetLab.Protocol', verbose_name='Growth protocol'),
        ),
    ]
