# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-25 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0061_auto_20170426_1541'),
        ('wetLab', '0073_auto_20170725_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biosample',
            name='protocols_additional',
        ),
        migrations.AddField(
            model_name='biosample',
            name='authentication_docs',
            field=models.ManyToManyField(blank=True, help_text='Attach any authentication document for your biosample here. e.g. Fragment Analyzer document, Gel images.', related_name='bioAddProto', to='wetLab.Protocol', verbose_name='Protocols_additional'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='protocol_type',
            field=models.ForeignKey(blank=True, help_text='The category that best describes the protocol or document.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protoChoice', to='organization.Choice'),
        ),
    ]
