# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-25 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wetLab', '0074_auto_20170725_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biosample',
            name='authentication_docs',
            field=models.ManyToManyField(blank=True, help_text='Attach any authentication document for your biosample here. e.g. Fragment Analyzer document, Gel images.', related_name='bioAddProto', to='wetLab.Protocol', verbose_name='authentication_docs'),
        ),
    ]
