# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-27 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wetLab', '0075_auto_20170725_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biosample',
            name='authentication_docs',
        ),
        migrations.AddField(
            model_name='biosample',
            name='protocols_additional',
            field=models.ManyToManyField(blank=True, help_text='Protocols describing deviations from 4DN SOPs, including additional culture manipulations eg. stem cell differentiation or cell cycle synchronization if they do not follow recommended 4DN SOPs', related_name='bioAddProto', to='wetLab.Protocol'),
        ),
    ]
